"""Minimal synchronous interfaces; P2 will add the actual Runner."""
from typing import Mapping, Protocol
from .model import Action, BackendConfig, CleanupResult, ExecutionResult, PlatformObservation, StepRecord, TaskProgress, TaskSpec

class Agent(Protocol):
    def reset(self, task: TaskSpec, initial_observation: PlatformObservation) -> None: ...
    def act(self, observation: PlatformObservation) -> Action: ...
    def close(self) -> None: ...

class Backend(Protocol):
    def reset(self, config: BackendConfig, task: TaskSpec) -> PlatformObservation: ...
    def observe(self) -> PlatformObservation: ...
    def execute(self, action: Action) -> ExecutionResult: ...
    def cleanup(self) -> CleanupResult: ...
    def close(self) -> None: ...

class Task(Protocol):
    def reset(self, spec: TaskSpec, initial_observation: PlatformObservation) -> None: ...
    def update(self, step: StepRecord) -> TaskProgress: ...
    def close(self) -> None: ...

class Evaluator(Protocol):
    def evaluate(self, steps: tuple[StepRecord, ...], progress: TaskProgress) -> Mapping[str, float]: ...
